doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        driver: 'pdo_mysql'
        server_version: 'mariadb-10.2.32'
        charset: utf8mb4
        default_table_options:
          charset: utf8mb4
          collate: utf8mb4_unicode_ci
        url: '%env(resolve:DATABASE_URL)%'
        mapping_types:
          enum: string
  orm:
    default_entity_manager: default
    auto_generate_proxy_classes: '%kernel.debug%'
    entity_managers:
      default:
        query_cache_driver:
          type: pool
          pool: app.cache.doctrine
        metadata_cache_driver:
          type: pool
          pool: app.cache.doctrine
        result_cache_driver:
          type: pool
          pool: app.cache.doctrine
        second_level_cache:
          region_cache_driver:
            type: service
            id: app.cache.doctrine
          enabled: true
        connection: default
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
          App:
            is_bundle: false
            type: attribute
            dir: '%kernel.project_dir%/src/Entity'
            prefix: 'App\Entity'
            alias: App
        dql:
          string_functions:
            date_format: Oro\ORM\Query\AST\Functions\String\DateFormat
          numeric_functions:
            rand: DoctrineExtensions\Query\Mysql\Rand
