fos_rest:
  view:
    view_response_listener: 'force'
    formats:
      xml: false
      json: true
  format_listener:
    rules:
      - { path: '^/api', priorities: [ 'json' ], fallback_format: 'json', prefer_extension: true }
      - { path: '^/', fallback_format: 'html', prefer_extension: true }
