framework:
  secret: '%env(APP_SECRET)%'
  session:
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax
    name: PHPSESSID_INTRANET
    gc_probability: null

  php_errors:
    log: true

  assets:
    version_format: "%%s?v=%%s"
    version: 20190118
  web_link:
    enabled: true

  disallow_search_engine_index: true

  serializer:
    circular_reference_handler: App\Serializer\CircularReferenceHandler

when@prod:
  framework:
    error_controller: App\Controller\ExceptionController::showException
