liip_imagine:
  resolvers:
    default:
      web_path:
        web_root: "%kernel.project_dir%/public"
        cache_prefix: "media/cache"
  loaders:
    default:
      filesystem:
        data_root: "%kernel.project_dir%/uploads"
  driver: gd
  filter_sets:
    avatar:
      quality: 75
      filters:
        thumbnail:
          size: [ 64, 64 ]
          mode: outbound
          allow_upscale: true
    box:
      quality: 75
      filters:
        thumbnail:
          size: [ 792, 446 ]
          mode: inset
          allow_upscale: false
    popup:
      quality: 75
      filters:
        thumbnail:
          size: [ 640, 480 ]
          mode: inset
          allow_upscale: false
    carousel:
      quality: 75
      filters:
        thumbnail:
          size: [ 1170, 585 ]
          mode: inset
          allow_upscale: false